confirm-before-quit = false
bindings.keys = [
  { key = "n", with = "control", action = "SelectNextTab" },
  { key = "p", with = "control", action = "SelectPrevTab" },
  { key = "d", with = "alt", action = "ScrollHalfPageDown" },
  { key = "u", with = "alt", action = "ScrollHalfPageUp" },
  { key = "x", with = "control | shift", action = "CloseTab" },
  { key = "=", with = "control | shift", action = "IncreaseFontSize" },
  { key = "-", with = "control", action = "DecreaseFontSize" },
  { key = "f", with = "control", action = "SearchForward" },
  { key = "b", with = "control", action = "SearchBackward" },
  { key = "=", with = "control", action = "ResetFontSize" },
  { key = "F11", action = "ToggleFullScreen" },
  { key = "\\", with = "control", action = "ToggleVIMode" },
  ### to find out which bytes correspond to which control sequences, use `showkey -a`
  # delete word backward
  { key = "back", with = "control", bytes = [
    23,
  ] },
  # delete word forward
  { key = "back", with = "shift", bytes = [
    27,
    100,
  ] },
  # delete line until the end
  { key = "back", with = "control | shift", bytes = [
    11,
  ] },
  # delete line until beginning
  { key = "back", with = "shift | control", bytes = [
    21,
  ] },
]

[fonts]
size = 19
regular.family = "JetBrainsMono NF"
bold.family = "JetBrainsMono NF"
italic.family = "JetBrainsMono NF"
bold-italic.family = "JetBrainsMono NF"

### catppuccin theme

[colors]
# Normal
foreground = '#cdd6f4'
background = '#1e1e2e'
black = '#45475a'
blue = '#89b4fa'
cursor = '#f5e0dc'
vi-cursor = '#f5e0dc'
cyan = '#94e2d5'
green = '#a6e3a1'
magenta = '#f5c2e7'
red = '#f38ba8'
white = '#bac2de'
yellow = '#f9e2af'
# UI colors
tabs = '#b4Befe'
tabs-active = '#b4befe'
selection-foreground = '#1e1e2e'
selection-background = '#f5e0dc'
# Dim colors
dim-black = '#45475a'
dim-blue = '#89b4fa'
dim-cyan = '#94e2d5'
dim-foreground = '#cdd6f4'
dim-green = '#a6e3a1'
dim-magenta = '#f5c2e7'
dim-red = '#f38ba8'
dim-white = '#bac2de'
dim-yellow = '#f9e2af'
# Light colors
light-black = '#585b70'
light-blue = '#89b4fa'
light-cyan = '#94e2d5'
light-foreground = '#cdd6f4'
light-green = '#a6e3a1'
light-magenta = '#f5c2e7'
light-red = '#f38ba8'
light-white = '#a6adc8'
light-yellow = '#f9e2af'
