[package]
name = "dotfiles_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
anstyle = "1.0.11"
env_logger = "0.11.8"
handlebars = "6.3.2"
log = "0.4.27"
sha256 = "1.6.0"
simply_colored = "0.1.0"
tap = "1.0.1"
ureq = "3.0.12"
walkdir = "2.5.0"
