# @dotfilers --path "{config}/rio/config.toml"
confirm-before-quit = false
use-fork = false
[[bindings.keys]]
action = "SelectNextTab"
key = "n"
with = "control"

[[bindings.keys]]
action = "SelectPrevTab"
key = "p"
with = "control"

[[bindings.keys]]
action = "ScrollHalfPageDown"
key = "d"
with = "alt"

[[bindings.keys]]
action = "ScrollHalfPageUp"
key = "u"
with = "alt"

[[bindings.keys]]
action = "CloseTab"
key = "x"
with = "control | shift"

[[bindings.keys]]
action = "IncreaseFontSize"
key = "="
with = "control | shift"

[[bindings.keys]]
action = "DecreaseFontSize"
key = "-"
with = "control"

[[bindings.keys]]
action = "SearchForward"
key = "f"
with = "control | shift"

[[bindings.keys]]
action = "SearchBackward"
key = "b"
with = "control | shift"

[[bindings.keys]]
action = "ResetFontSize"
key = "="
with = "control"

[[bindings.keys]]
action = "ToggleFullScreen"
key = "F11"

[[bindings.keys]]
action = "ToggleVIMode"
key = "\\"
with = "control"

[[bindings.keys]]
bytes = [23]
key = "back"
with = "control"

[[bindings.keys]]
bytes = [27, 100]
key = "back"
with = "shift"

[[bindings.keys]]
bytes = [11]
key = "back"
with = "control | shift"

[[bindings.keys]]
bytes = [21]
key = "back"
with = "shift | control"

[colors]
background = "#1e1e2e"
black = "#45475a"
blue = "#89b4fa"
cursor = "#f5e0dc"
cyan = "#94e2d5"
dim-black = "#45475a"
dim-blue = "#89b4fa"
dim-cyan = "#94e2d5"
dim-foreground = "#cdd6f4"
dim-green = "#a6e3a1"
dim-magenta = "#f5c2e7"
dim-red = "#f38ba8"
dim-white = "#bac2de"
dim-yellow = "#f9e2af"
foreground = "#cdd6f4"
green = "#a6e3a1"
light-black = "#585b70"
light-blue = "#89b4fa"
light-cyan = "#94e2d5"
light-foreground = "#cdd6f4"
light-green = "#a6e3a1"
light-magenta = "#f5c2e7"
light-red = "#f38ba8"
light-white = "#a6adc8"
light-yellow = "#f9e2af"
magenta = "#f5c2e7"
red = "#f38ba8"
selection-background = "#f5e0dc"
selection-foreground = "#1e1e2e"
tabs = "#b4Befe"
tabs-active = "#b4befe"
vi-cursor = "#f5e0dc"
white = "#bac2de"
yellow = "#f9e2af"

[fonts]
family = "JetBrainsMono Nerd Font"
size = 23
[[fonts.emojis]]
family = "Noto Color Emoji"

[[fonts.extras]]
family = "Noto Sans Mono CJK JP"

[navigation]
use-current-path = true
