{{#* inline "rebindings" }}
# rebindings because default keymap is awkward with my custom keyboard layout
# DEFAULT: A-C
A-c = "copy_selection_on_prev_line"
# DEFAULT: A-J
C-j = "join_selections_space"
# DEFAULT: A-K
C-k = "remove_selections"
# DEFAULT: A-I
C-c = "select_all_children"
# DEFAULT: A-n
A-right = "select_next_sibling"
# DEFAULT: A-U
C-S-u = "later"
{{/inline}}

theme = "catppuccin"

[editor]
auto-info = false
completion-timeout = 5
cursorline = true
# uses system clipboard
default-yank-register = "+"
idle-timeout = 5
line-number = "relative"

[editor.indent-guides]
character = "╎"
render = true
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.lsp]
auto-signature-help = false

[editor.smart-tab]
enable = false

[editor.soft-wrap]
enable = true

[editor.statusline]
center = []
left = []
right = ["spinner", "file-name", "diagnostics"]

[keys.insert]
A-ret = ["insert_newline", "delete_word_backward"]

[keys.normal]
C-e = [":write-all", ":insert-output scooter >/dev/tty", ":redraw", ":reload-all"]
C-g = [":write-all", ":insert-output lazygit >/dev/tty", ":redraw", ":reload-all"]
S-left = "jump_backward"
S-right = "jump_forward"
X = "select_line_above"
# --- newline without comment
backspace = "goto_word"
# ---
down = "select_textobject_around"
left = "@["
ret = ":write"
right = "@]"
tab = "collapse_selection"
up = "select_textobject_inner"
x = "select_line_below"
g.O = ["open_above", "delete_word_backward"]
g.o = ["open_below", "delete_word_backward"]
m."\"" = "@f\";vmmdi\""
m."'" = "@f';vmmdi'"
m."(" = "@f);vmmdi("
m."<" = "@f<gt>;vmmdi<lt><gt><left>"
m."[" = "@f];vmmdi["
m."{" = "@f};vmmdi{"
space.C-d = "@<space>D%severity ERROR "
space.E = [":sh rm -f /tmp/unique-file-h21a434", ":insert-output yazi '%{workspace_directory}' --chooser-file=/tmp/unique-file-h21a434", ":insert-output echo \"x1b[?1049h\" > /dev/tty", ":open %sh{cat /tmp/unique-file-h21a434}", ":redraw"]
space.X = ":write-quit-all!"
space.e = [":sh rm -f /tmp/unique-file-u41ae14", ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-u41ae14", ":insert-output echo \"x1b[?1049h\" > /dev/tty", ":open %sh{cat /tmp/unique-file-u41ae14}", ":redraw"]
space.x = ":write-quit-all"

{{> rebindings }}

[keys.select]
C-e = [":write-all", ":insert-output scooter >/dev/tty", ":redraw", ":reload-all"]
C-g = [":write-all", ":insert-output lazygit >/dev/tty", ":redraw", ":reload-all"]
S-left = "jump_backward"
S-right = "jump_forward"
X = "select_line_above"
backspace = "extend_to_word"
down = "select_textobject_around"
left = "@["
ret = ":write"
right = "@]"
tab = "collapse_selection"
up = "select_textobject_inner"
x = "select_line_below"
# --- newline without comment
g.O = ["open_above", "delete_word_backward"]
g.o = ["open_below", "delete_word_backward"]
# ---
space.C-d = "@<space>D%severity ERROR "
space.E = [":sh rm -f /tmp/unique-file-h21a434", ":insert-output yazi '%{workspace_directory}' --chooser-file=/tmp/unique-file-h21a434", ":insert-output echo \"x1b[?1049h\" > /dev/tty", ":open %sh{cat /tmp/unique-file-h21a434}", ":redraw"]
space.X = ":write-quit-all!"
space.e = [":sh rm -f /tmp/unique-file-u41ae14", ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-u41ae14", ":insert-output echo \"x1b[?1049h\" > /dev/tty", ":open %sh{cat /tmp/unique-file-u41ae14}", ":redraw"]
space.x = ":write-quit-all"
m."\"" = "@f\";vmmdi\""
m."'" = "@f';vmmdi'"
m."(" = "@f);vmmdi("
m."<" = "@f<gt>;vmmdi<lt><gt><left>"
m."[" = "@f];vmmdi["
m."{" = "@f};vmmdi{"

{{> rebindings }}
