theme = "catppuccin"

[editor]
auto-info = false
completion-timeout = 5
cursorline = true
# use system clipboard
default-yank-register = "+"
idle-timeout = 5
line-number = "relative"
inline-diagnostics.cursor-line = "hint"
lsp.auto-signature-help = false
smart-tab.enable = false
soft-wrap.enable = true

[editor.indent-guides]
character = "╎"
render = true
skip-levels = 1

[keys.insert]
# newline without continue comment
A-ret = ["insert_newline", "delete_word_backward"]

{{#* inline "shared" }}

# --- newline without continue comment
g.O = ["open_above", "delete_word_backward"]
g.o = ["open_below", "delete_word_backward"]
# ---

"{" = ["goto_next_paragraph"]
"}" = ["goto_prev_paragraph"]

ret = ":write"

space.C-d = "@<space>D%severity ERROR "
S-left = "jump_backward"
S-right = "jump_forward"

x = "select_line_below"
X = "select_line_above"
space.x = ":write-quit-all"
space.X = ":write-quit-all!"

tab = "collapse_selection"
up = "select_textobject_inner"
down = "select_textobject_around"
left = "@["
right = "@]"

# scooter integration
C-e = [
  ":write-all",
  ":insert-output scooter >/dev/tty",
  ":redraw",
  ":reload-all"
]
# lazygit integration
C-g = [
  ":write-all",
  ":insert-output lazygit >/dev/tty",
  ":redraw",
  ":reload-all"
]
# --- yazi integration
space.e = [
  ":sh rm -f /tmp/unique-file-u41ae14",
  ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-u41ae14",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-u41ae14}",
  ":redraw"
]
space.E = [
  ":sh rm -f /tmp/unique-file-h21a434",
  ":insert-output yazi '%{workspace_directory}' --chooser-file=/tmp/unique-file-h21a434",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-h21a434}",
  ":redraw"
]
# ---

# rebindings because default keymap is awkward with my custom keyboard layout
# DEFAULT: A-C
A-c = "copy_selection_on_prev_line"
# DEFAULT: A-J
C-j = "join_selections_space"
# DEFAULT: A-K
C-k = "remove_selections"
# DEFAULT: A-I
C-c = "select_all_children"
# DEFAULT: A-n
A-right = "select_next_sibling"
# DEFAULT: A-U
C-S-u = "later"
#{{/inline}}

[keys.normal]
backspace = "goto_word"
#{{> shared }}

[keys.select]
backspace = "extend_to_word"
#{{> shared }}
