[[language]]
auto-format = true
name = "nix"
formatter.command = "nixfmt"

[language.auto-pairs]
"=" = ";"
# unchanged:
"\"" = "\""
"'" = "'"
"(" = ")"
"[" = "]"
"`" = "`"
"{" = "}"

[language-server.rust-analyzer.config.check]
command = "clippy"

# for clippy development
# [language-server.rust-analyzer.config.rustc]
# source = "discover"
